### ISSUE TITLE
Zig 0.15.1 compatibility

### ISSUE THREAD

**Issue by PsychoB00** [zigzap/zap#175]
The new version of zig no longer has Build.addStaticLibrary.
I get compile error on: "facil.io/build.zig:10:18"

**Comment by bgaster** [comment]
I'm sure there is, I just for some reason can't find it. Probably something I'm just being silly about, but anyway.

**Comment by renerocksai** [comment]
Sorry for the confusion. I had replied to the question: "Is there a plan...?"; the answer is yes, there is a plan. It just hasn't been implemented yet. Zig 0.15.1 requires a lot of changes and I don't have time for that right now; I hope to have time for it soon.

Viable options IMHO : stick to 0.14.1 for now
Check out PR #173 

You're not being silly. It's just work that hasn't been done yet. I'll probably merge #173 when I update to 0.15.1.

**Comment by p-marcin** [comment]
Hello, for anyone struggling with the demo on https://zigzap.org/learn.html

You should use `zig fetch --save "git+https://github.com/zigzap/zap#v0.11.0"`, so latest version of Zap obviously and you need to change this line in `src/main.zig`:

```zig
fn on_request(r: zap.Request) void {
```
to
```zig
fn on_request(r: zap.Request) !void {
```
due to compile error:
```shell
$ zig build run
run
└─ run exe foo
   └─ compile exe foo Debug native 1 errors
src/main.zig:19:10: error: expected type '*const fn (request) anyerror!void', found '*const fn (request) void'
        .on_request = on_request,
```

---

Also this part was not clear to me where exactly I should put it:
```zig
const zap = b.dependency("zap", .{
    .target = target,
    .optimize = optimize,
    .openssl = false, // set to true to enable TLS support
});
exe.root_module.addImport("zap", zap.module("zap"));
```
It should be added in the function:
```zig
pub fn build(b: *std.Build) void {
```
before `b.installArtifact(exe)` line.

---

I used Zig `0.15.2` BTW.

I'm new to both Zig and Zap, so I figured this might help others - especially since the demo is one of the first things newcomers will try.
